CURSEFORGE_API_KEY=9ac5a4b4-9253-4663-9f47-17a339511221
MODRINTH_API_KEY=mrp_fv9q4KMvXLpNK4bkOVCil3E2TESIUnZIdManOmh0tnEv9UsAqffMKaoO7O9z
GITHUB_API_KEY=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